import logging
import requests
import os

logger = logging.getLogger("HF_GENERATOR")
logging.basicConfig(level=logging.INFO, format="%(asctime)s | HF_GENERATOR | %(levelname)s | %(message)s")

# Read the HuggingFace API URL from environment (if set)
HF_URL = os.getenv("HF_URL", "http://127.0.0.1:8010/generate")

def generate_app_code(prompt: str) -> str:
    """
    Generate HTML app code based on a given prompt.
    If HF_URL is not reachable (like on Render), returns a mock HTML page.
    """

    logger.info(f"🧠 Sending prompt to HuggingFace server: {HF_URL}")

    try:
        # Try connecting to actual HuggingFace generator
        response = requests.post(HF_URL, json={"prompt": prompt}, timeout=20)

        if response.status_code == 200:
            try:
                data = response.json()
                logger.info("✅ Code generation completed successfully.")
                return data.get("code", data.get("html", "<h1>Generated: OK</h1>"))
            except ValueError:
                # Not valid JSON → fallback to raw text
                logger.warning("⚠️ HF output not valid JSON, returning as single file.")
                return response.text

        else:
            logger.error(f"❌ HF generation failed with status {response.status_code}")
            return _mock_html(prompt)

    except Exception as e:
        # On Render, the 127.0.0.1:8010 endpoint won’t exist → fallback safely
        logger.error(f"❌ HF request failed: {e}")
        return _mock_html(prompt)


def _mock_html(prompt: str) -> str:
    """
    Mock LLM HTML generator for Render environment.
    Returns a valid HTML structure to simulate app creation.
    """
    logger.info(f"⚙️ Using mock generator for Render environment...")
    html_code = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>LLM Generated App</title>
        <style>
            body {{
                font-family: Arial, sans-serif;
                background-color: #f9f9f9;
                color: #222;
                padding: 40px;
                text-align: center;
            }}
            h1 {{
                color: #0078D7;
            }}
            .footer {{
                margin-top: 40px;
                font-size: 14px;
                color: #777;
            }}
        </style>
    </head>
    <body>
        <h1>LLM Deployment Demo</h1>
        <p>Prompt received:</p>
        <blockquote>{prompt}</blockquote>
        <p>This is a mock HTML page generated automatically on Render.</p>
        <div class="footer">
            <p>Generated by: <strong>H4D3S21 LLM App Generator</strong></p>
        </div>
    </body>
    </html>
    """
    return html_code
